@startuml

participant 业务系统
participant 交易系统
participant 交易平台
业务系统->交易系统:发起客户登录
alt 交易平台存在客户登录
交易系统->交易平台:发起客户登录
交易平台->交易平台:客户登录
alt 登录成功
交易平台-->交易系统:返回客户登录成功
交易系统-->业务系统:返回客户登录成功
else 登录失败
交易平台-->交易系统:返回客户登录失败及失败原因
交易系统-->业务系统:返回客户登录失败及失败原因
end
else 交易平台不存在客户登录
交易系统->交易平台:判断客户交易账户是否存在
alt 交易账户存在，登录成功
交易平台-->交易系统:返回客户登录成功
交易系统-->业务系统:返回客户登录成功
else 交易账户不存在，登录失败
交易平台-->交易系统:返回客户登录失败及失败原因
交易系统-->业务系统:返回客户登录失败及失败原因
end
end

@enduml